/**
 * AI Usage Model
 *
 * Per-project, per-month meter for AI-backed work (translate + voice). Each
 * document is one (projectId, period) bucket, where `period` is a "YYYY-MM"
 * string in UTC. The route layer increments the counters atomically via
 * $inc upserts (see utils/usage.ts), so concurrent AI calls never lose a count.
 *
 * The monthly credit cap (Project.aiMonthlyCap) is enforced against
 * `keysTranslated` for the current period — a single project can't silently
 * run up the model bill.
 *
 * Counters:
 *   - aiCalls         total AI provider invocations (translate + voice) this month
 *   - keysTranslated  number of keys actually written by /ai-translate this month
 *   - voiceCalls      number of voice cells actually generated by /generate-voice
 */

import mongoose, { Schema } from "mongoose";

const aiUsageSchema = new Schema({
  projectId: {
    type: Schema.Types.ObjectId,
    ref: "Project",
    required: true,
    index: true,
  },
  // "YYYY-MM" (UTC). One bucket per project per calendar month.
  period: { type: String, required: true },
  // Number of AI provider calls (translate batches + voice). Advisory metric.
  aiCalls: { type: Number, default: 0 },
  // Number of translation keys actually written by /ai-translate. This is the
  // quantity the monthly cap is enforced against.
  keysTranslated: { type: Number, default: 0 },
  // Number of voice cells actually generated by /generate-voice.
  voiceCalls: { type: Number, default: 0 },
  updatedAt: { type: Date, default: Date.now },
});

// One row per (project, month). The unique index is also what makes the
// $inc upsert in recordUsage() race-safe: concurrent upserts collapse onto
// the same document instead of creating duplicates.
aiUsageSchema.index({ projectId: 1, period: 1 }, { unique: true });

const AiUsage = mongoose.model("AiUsage", aiUsageSchema);

export default AiUsage;
